const Discord = require('discord.js')
const bot = new Discord.Client()

bot.login('NTYwMDUwMTg0ODAxNzQ2OTQ0.D3uhOg.hgQtgrS5NEBLi634xF4MT6Rr62w')

bot.on('message', message => {

    if(message.content === 'ping')
       message.channel.send("pong")
    if(message.content === 'lol')
       message.channel.send("mdr")
    if(message.content === 'bonjour')
       message.channel.send("bonjour comment allez-vous")
    if(message.content === 'qui est ton créateur ?')
       message.channel.send("moji-wings")
    if(message.content === 'emoji 1')
       message.channel.send(":sob:")
    if(message.content === 'bien')
       message.channel.send("daccord")
    if(message.content === 'qui êtes-vous ?')
       message.channel.send("je suis un bot nommé PSY , j'ai une intelligence artificielle . J'ai été développé par moji-wings")
    if(message.content === 'PSY123')
       message.channel.send("@everyone :warning: ici vous êtes dans le salon pour me développer . Pour m'aider a être plus intelligent envoyez moi des questions avec des réponses , ex : bonjour (le robot répond :) bonjour . Ne mettez pas des questions deja mise sur le robot . ")
    if(message.content === 'tg')
       message.channel.send("OK ferme la aussi")
    if(message.content === '!joue')
       message.channel.send("cet fonctionnalité n'est pas encore valide mais va être mis bientôt")
    if(message.content === 'Tes une pute')
       message.channel.send("Je suis ton père pas ta mère")
    if(message.content === 'Ca va ?')
       message.channel.send("Oui et toi")
    if(message.content === 'Non')
       message.channel.send("pourquoi ?")
    if(message.content === 'non')
       message.channel.send("pourquoi ?")
    if(message.content === 'nn')
       message.channel.send("pourquoi ?")
    if(message.content === 'oui')
       message.channel.send("ok")
    if(message.content === 'TK78')
       message.channel.send("Vos mères c'est des dinosaures")
    if(message.content === 'G une bite')
       message.channel.send("Tes parents ton jamais appris a dire la vérité")
    if(message.content === 'Aimes-tu Fortnite Stats ?')
       message.channel.send("Bof il a l'air con :sweat_smile:")
    if(message.content === '!fm moji-wings')
       message.channel.send(":x: An error occured voila ce que répond le bot débile ...")
})
